<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<ProjectExperiment>
		<window>
			<RelativeDocumentPlacement type="key">1:m 0 Instrumentation|48280072-60fc-4d7a-b18c-c7c6803e0ea3/4:</RelativeDocumentPlacement>
		</window>
		<viewflags>
			<Name type="key">Brakes_Modes_v1.CDE</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">Brakes_Modes_v1</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment Layouts</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">Brakes_Modes_v1.cdc</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">Layout1.lay</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Hardware Configurations</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">f2d9cb66-2417-40b1-a2ab-1ed6fbb77a6f</Name>
						<ViewFlags type="key">1</ViewFlags>
						<item>
							<Name type="key">sds_mod_v1.sdf</Name>
							<ViewFlags type="key">5</ViewFlags>
							<item>
								<Name type="key">Data Sets</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
						</item>
					</item>
				</item>
				<item>
					<Name type="key">Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Measurement Data</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">cv.vxf</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Reports</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Python Scripts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Signal Generators</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">XIL API EESPorts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">Events</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment.events</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
		</viewflags>
	</ProjectExperiment>
	<SignalEditor>
		<OpenSignalDescriptionSets Version="1"/>
		<OpenSignalGenerators Version="1"/>
		<Documents Version="1"/>
	</SignalEditor>
	<Interpreter Version="2">
		<Project>
			<ScriptCount type="key">0</ScriptCount>
		</Project>
		<Experiment>
			<ScriptCount type="key">0</ScriptCount>
		</Experiment>
	</Interpreter>
	<Instrumentation>
		<Layouts Version="3">
			<Layout1>
				<Data type="key">Layout1.lay|1|48280072-60fc-4d7a-b18c-c7c6803e0ea3/4|1:sm:mm 78 78 1805 744 -1 -1:</Data>
			</Layout1>
		</Layouts>
	</Instrumentation>
	<XILAPIEESPort>
		<ErrorConfigurationDocuments Version="1"/>
	</XILAPIEESPort>
</Root>