<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<ProjectExperiment>
		<window>
			<RelativeDocumentPlacement type="key">1:m 0 Instrumentation|27f6d246-946f-4f3f-b64b-2db6cccf85a8/0:</RelativeDocumentPlacement>
		</window>
		<viewflags>
			<Name type="key">brk_cbc.CDE</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">brk_cbc</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment Layouts</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">brk_cbc.cdc</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">Layout1.lay</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Hardware Configurations</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">a86aab27-d9d9-4d5b-a11b-1dbda64d3463</Name>
						<ViewFlags type="key">1</ViewFlags>
						<item>
							<Name type="key">sds_brk_cbc_v1.sdf</Name>
							<ViewFlags type="key">5</ViewFlags>
							<item>
								<Name type="key">Data Sets</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
						</item>
					</item>
				</item>
				<item>
					<Name type="key">Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Measurement Data</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">cv.vxf</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Reports</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Python Scripts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Signal Generators</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">XIL API EESPorts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">Events</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment.events</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
		</viewflags>
	</ProjectExperiment>
	<XILAPIEESPort>
		<ErrorConfigurationDocuments Version="1"/>
	</XILAPIEESPort>
	<SignalEditor>
		<OpenSignalDescriptionSets Version="1"/>
		<OpenSignalGenerators Version="1"/>
		<Documents Version="1"/>
	</SignalEditor>
	<Interpreter Version="2">
		<Project>
			<ScriptCount type="key">0</ScriptCount>
		</Project>
		<Experiment>
			<ScriptCount type="key">0</ScriptCount>
		</Experiment>
	</Interpreter>
	<Instrumentation>
		<Layouts Version="3">
			<Layout1>
				<Data type="key">Layout1.lay|1|27f6d246-946f-4f3f-b64b-2db6cccf85a8/0|1:sm:mm 32 32 1782 601 -1 -1:</Data>
			</Layout1>
		</Layouts>
	</Instrumentation>
</Root>