<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<ProjectExperiment>
		<window>
			<RelativeDocumentPlacement type="key">1:m 0 Instrumentation|12e23f82-7a81-4c7a-973c-e62ee24bf312/3:</RelativeDocumentPlacement>
		</window>
		<viewflags>
			<Name type="key">CBC_SDS_mode_v1.CDE</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">CBC_SDS_mode_v1</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment Layouts</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">CBC_SDS_mode_v1.cdc</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">Autonomy_SDS_CBC.lay</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Hardware Configurations</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">9dcc0397-9639-44bd-8aba-433fb68cfaa3</Name>
						<ViewFlags type="key">1</ViewFlags>
						<item>
							<Name type="key">sds_mod_v1.sdf</Name>
							<ViewFlags type="key">5</ViewFlags>
							<item>
								<Name type="key">Data Sets</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
						</item>
					</item>
				</item>
				<item>
					<Name type="key">Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Measurement Data</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">cv.vxf</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Reports</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Python Scripts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Signal Generators</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">XIL API EESPorts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">Events</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment.events</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
		</viewflags>
	</ProjectExperiment>
	<SignalEditor>
		<OpenSignalDescriptionSets Version="1"/>
		<OpenSignalGenerators Version="1"/>
		<Documents Version="1"/>
	</SignalEditor>
	<Interpreter Version="2">
		<Project>
			<ScriptCount type="key">0</ScriptCount>
		</Project>
		<Experiment>
			<ScriptCount type="key">0</ScriptCount>
		</Experiment>
	</Interpreter>
	<Instrumentation>
		<Layouts Version="3">
			<Layout1>
				<Data type="key">Autonomy_SDS_CBC.lay|1|12e23f82-7a81-4c7a-973c-e62ee24bf312/3|1:sm:mm -153 111 1574 646 -1 -1:</Data>
			</Layout1>
		</Layouts>
	</Instrumentation>
	<XILAPIEESPort>
		<ErrorConfigurationDocuments Version="1"/>
	</XILAPIEESPort>
</Root>