<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<ProjectExperiment>
		<window>
			<RelativeDocumentPlacement type="key">1:m 0 Instrumentation|5fab532a-97a6-4c18-b6f6-c9525f23efc7/1:</RelativeDocumentPlacement>
		</window>
		<viewflags>
			<Name type="key">Campari_copy.CDE</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">Campari_copy</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment Layouts</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">Campari_copy.cdc</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">Layout1.lay</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Hardware Configurations</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">08ded523-1a61-4259-bbc9-573217b8a7ff</Name>
						<ViewFlags type="key">1</ViewFlags>
						<item>
							<Name type="key">campari_gatewaytest_mabxii.sdf</Name>
							<ViewFlags type="key">1</ViewFlags>
							<item>
								<Name type="key">Data Sets</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
						</item>
					</item>
				</item>
				<item>
					<Name type="key">Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Measurement Data</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">cv.vxf</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Reports</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Python Scripts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Signal Generators</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">XIL API EESPorts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">Events</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment.events</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
		</viewflags>
	</ProjectExperiment>
	<XILAPIEESPort>
		<ErrorConfigurationDocuments Version="1"/>
	</XILAPIEESPort>
	<SignalEditor>
		<OpenSignalDescriptionSets Version="1"/>
		<OpenSignalGenerators Version="1"/>
		<Documents Version="1"/>
	</SignalEditor>
	<Interpreter Version="2">
		<Project>
			<ScriptCount type="key">0</ScriptCount>
		</Project>
		<Experiment>
			<ScriptCount type="key">0</ScriptCount>
		</Experiment>
	</Interpreter>
	<Instrumentation>
		<Layouts Version="3">
			<Layout1>
				<Data type="key">Layout1.lay|1|5fab532a-97a6-4c18-b6f6-c9525f23efc7/1|1:sm:mm 78 78 2330 613 -1 -1:</Data>
			</Layout1>
		</Layouts>
	</Instrumentation>
</Root>