<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<Interpreter Version="2">
		<Project>
			<ScriptCount type="key">0</ScriptCount>
		</Project>
	</Interpreter>
	<ProjectExperiment>
		<viewflags>
			<Name type="key">SDS_mode_v1.CDP</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">SDS_mode_v1</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Specifications</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Project Plans</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Global Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Variable Descriptions</Name>
					<ViewFlags type="key">0</ViewFlags>
					<item>
						<Name type="key">SDS_mode_v1.vdb</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">sds_mod_v1.sdf</Name>
						<ViewFlags type="key">0</ViewFlags>
						<item>
							<Name type="key">sds_mod_v1.trc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">sds_mod_v1.map</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">sds_mod_v1.ppc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
					</item>
					<item>
						<Name type="key">campari_gatewaytest_mabxii.sdf</Name>
						<ViewFlags type="key">0</ViewFlags>
						<item>
							<Name type="key">campari_gatewaytest_mabxii.trc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">campari_gatewaytest_mabxii.map</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">campari_gatewaytest_mabxii.ppc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">campari_gatewaytest_mabxii.trz</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
					</item>
					<item>
						<Name type="key">campari_sim9.sdf</Name>
						<ViewFlags type="key">0</ViewFlags>
						<item>
							<Name type="key">campari_sim9.trc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">campari_sim9.map</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">campari_sim9.ppc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
					</item>
					<item>
						<Name type="key">sds_mod_v1.sdf</Name>
						<ViewFlags type="key">0</ViewFlags>
						<item>
							<Name type="key">sds_mod_v1.trc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">sds_mod_v1.map</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">sds_mod_v1.ppc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
					</item>
					<item>
						<Name type="key">sds_mod_v1.sdf</Name>
						<ViewFlags type="key">0</ViewFlags>
						<item>
							<Name type="key">sds_mod_v1.trc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">sds_mod_v1.map</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
						<item>
							<Name type="key">sds_mod_v1.ppc</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
					</item>
				</item>
				<item>
					<Name type="key">Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Variable Filters</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Label Lists</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Python Scripts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">BusNavigator</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Signal Description Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">Events</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Project.events</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
		</viewflags>
	</ProjectExperiment>
</Root>